import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import DashbordSlider from "../components/dashbord/DashbordSlider";
import WelcomeScreen from "../components/dashbord/WelcomeScreen";

const Home: NextPage<{ firstVisit: boolean }> = ({ firstVisit }) => {
  // const [firstVisit, setFirstVisit] = useState(false);
  // const [nav, setNav] = useState(false);

  // useEffect(() => {
  //   const userFirstVisit = sessionStorage.getItem("Has_visited");

  //   if (userFirstVisit !== "True") {
  //     console.log("use effect loop");
  //     setFirstVisit(true);
  //     sessionStorage.setItem("Has_visited", "True");
  //   }
  //   setTimeout(() => {
  //     setFirstVisit(false);
  //   }, 4000);
  // }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {firstVisit && <WelcomeScreen />}
      <DashbordSlider />
    </div>
  );
};

export default Home;
